package alasucu;


import alasucu.Trie.TArbolTrie;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Josse
 */
public class AlasUcuMain extends javax.swing.JFrame {
    
  

    /**
     * Creates new form TriePrefixAEDIIGUI
     */
    public AlasUcuMain() {
        
        initComponents();
        FacadeAlasUcu facade = FacadeAlasUcu.getInstance();
        
        this.iniciarBusqueda(jListPalabras, facade.getTrieAerolineas(), jtfSearch);
        this.iniciarBusqueda(jListAeropuertos1, facade.getTrieAeropuertos(), jSearchAeropuerto1);
        this.iniciarBusqueda(jListAeropuertos2, facade.getTrieAeropuertos(), jSearchAeropuerto2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPalabras = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListAeropuertos1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListAeropuertos2 = new javax.swing.JList<>();
        jSearchAeropuerto1 = new javax.swing.JTextField();
        jSearchAeropuerto2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnTodasAerolineas = new java.awt.Button();
        fieldEscalas = new java.awt.TextField();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione una Aerolinea:");

        jtfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSearchActionPerformed(evt);
            }
        });
        jtfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfSearchKeyReleased(evt);
            }
        });

        jLabel2.setText("Aerolineas");

        jScrollPane1.setViewportView(jListPalabras);

        jScrollPane2.setViewportView(jListAeropuertos1);

        jScrollPane3.setViewportView(jListAeropuertos2);

        jSearchAeropuerto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jSearchAeropuerto1KeyReleased(evt);
            }
        });

        jSearchAeropuerto2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jSearchAeropuerto2KeyReleased(evt);
            }
        });

        jLabel3.setText("Seleccione Origen");

        jLabel4.setText("Seleccione Destino");

        btnTodasAerolineas.setLabel("Todas las Aerolineas");
        btnTodasAerolineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodasAerolineasActionPerformed(evt);
            }
        });

        label1.setText("Escalas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfSearch)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                .addComponent(jSearchAeropuerto1))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(jSearchAeropuerto2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldEscalas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnTodasAerolineas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSearchAeropuerto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSearchAeropuerto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fieldEscalas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTodasAerolineas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSearchKeyReleased
       this.iniciarBusqueda(jListPalabras, FacadeAlasUcu.getInstance().getTrieAerolineas(), jtfSearch);
    }//GEN-LAST:event_jtfSearchKeyReleased

    private void jtfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSearchActionPerformed

    private void jSearchAeropuerto1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSearchAeropuerto1KeyReleased
        this.iniciarBusqueda(jListAeropuertos1, FacadeAlasUcu.getInstance().getTrieAeropuertos(), jSearchAeropuerto1);
    }//GEN-LAST:event_jSearchAeropuerto1KeyReleased

    private void jSearchAeropuerto2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSearchAeropuerto2KeyReleased
        this.iniciarBusqueda(jListAeropuertos2, FacadeAlasUcu.getInstance().getTrieAeropuertos(), jSearchAeropuerto2);
    }//GEN-LAST:event_jSearchAeropuerto2KeyReleased

    private void btnTodasAerolineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodasAerolineasActionPerformed
        FacadeAlasUcu facade = FacadeAlasUcu.getInstance();
        
        String aeropuerto1 = jListAeropuertos1.getSelectedValue().toString();
        String codAeropuerto1 = facade.getTrieAeropuertos().buscarEtiqueta(aeropuerto1).toString();
        
        String aeropuerto2 = jListAeropuertos2.getSelectedValue().toString();
        String codAeropuerto2 = facade.getTrieAeropuertos().buscarEtiqueta(aeropuerto2).toString();
        
        new MejoresTodasLasAerolineas(aeropuerto1,codAeropuerto1,aeropuerto2,codAeropuerto2,Integer.parseInt(fieldEscalas.getText())).setVisible(true);
    }//GEN-LAST:event_btnTodasAerolineasActionPerformed

    private void iniciarBusqueda(JList lista,TArbolTrie arbol,JTextField tfield){
        DefaultListModel listModel = new DefaultListModel();

        lista.clearSelection();
        LinkedList<String> palabras;
        //TODO: LLENAR LISTA DE PALABRAS CON EL MÉTODO PREDECIR
        palabras = arbol.predecir(tfield.getText());
        for(String palabra : palabras){
            listModel.addElement(palabra);
        }
        lista.setModel(listModel);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlasUcuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlasUcuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlasUcuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlasUcuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlasUcuMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnTodasAerolineas;
    private java.awt.TextField fieldEscalas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jListAeropuertos1;
    private javax.swing.JList<String> jListAeropuertos2;
    private javax.swing.JList jListPalabras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jSearchAeropuerto1;
    private javax.swing.JTextField jSearchAeropuerto2;
    private javax.swing.JTextField jtfSearch;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
