/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alasucu;

import alasucu.Utiles.TableRender;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.LinkedList;
import java.util.concurrent.LinkedBlockingDeque;
import javafx.scene.control.Cell;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author German
 */
public class MejoresTodasLasAerolineas extends javax.swing.JFrame {

    DefaultTableModel modeloTodosLosVuelos;
    
    /**
     * Creates new form MejoresTodasLasAerolineas
     */
    public MejoresTodasLasAerolineas(String origen,String aeropuerto1,String destino,String aeropuerto2,Integer cantEscalas) {
        FacadeAlasUcu fac = FacadeAlasUcu.getInstance();
        LinkedList<DataVuelo> vuelos = fac.todasLasAerolineas(aeropuerto1, aeropuerto2, cantEscalas);
        modeloTodosLosVuelos = new DefaultTableModel(null,getColumnas(vuelos));
        setFilas(vuelos,cantEscalas);
        initComponents();
        labelAeropuertoO.setText(origen);
        labelAeropuertoD.setText(destino);
        NroEscalas.setText(cantEscalas.toString());

        TOpcionVuelo optimo = fac.vueloOptimo(vuelos,cantEscalas);
        int i=0;
        for(DataVuelo v : vuelos){
            if(optimo==v.getVuelo()){
                tableVuelos.setDefaultRenderer(Object.class, new TableRender(i));
                break;
            }
            i++;
        }
    }

    private String[] getColumnas(LinkedList<DataVuelo> vuelos){
        FacadeAlasUcu fac = FacadeAlasUcu.getInstance();
        int tamanio=vuelos.size();
        String[] columnas = new String[tamanio];
        int i=0;
        for(DataVuelo v : vuelos){
            columnas[i++]=fac.getDescripcionAerolinea(v.getAerolinea());
        }
        
        return columnas;
    }
    
    private void setFilas(LinkedList<DataVuelo> vuelos, Integer cantEscalas){
        FacadeAlasUcu fac = FacadeAlasUcu.getInstance();
        int tamanio=vuelos.size();
        String[] datos = new String[tamanio];
        for(int i=0;i<cantEscalas+2;i++){
            
            int j=0;
            for(DataVuelo v : vuelos){
                if(i<cantEscalas){
                    if(i<v.getVuelo().getOtrosVertices().size()){
                        datos[j++]=fac.getDescripcionAeropuerto(v.getVuelo().getOtrosVertices().get(i));
                    }else{
                        datos[j++]="";
                    }
                }else{
                    /*La penultima fila, va libre - En la ultima el costo*/
                    if(i==cantEscalas){
                        datos[j++]="---------------------";
                    }else{
                        datos[j++]="Costo total: " + String.valueOf(v.getVuelo().getCosto());
                    }
                }
            }
            
            modeloTodosLosVuelos.addRow(datos);
        }
        

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelAeropuertoO = new java.awt.Label();
        jLabel6 = new javax.swing.JLabel();
        labelAeropuertoD = new java.awt.Label();
        labelEscalas = new java.awt.Label();
        NroEscalas = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableVuelos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(1000, 500));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel1.setText("Todas las Aerolineas");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Origen: ");

        labelAeropuertoO.setText("Origen");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Destino: ");

        labelAeropuertoD.setText("Destino");

        labelEscalas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelEscalas.setText("Escalas");

        NroEscalas.setText("NroEscalas");

        tableVuelos.setModel(modeloTodosLosVuelos);
        jScrollPane2.setViewportView(tableVuelos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAeropuertoO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAeropuertoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelEscalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NroEscalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(labelAeropuertoO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(labelAeropuertoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelEscalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NroEscalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MejoresTodasLasAerolineas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MejoresTodasLasAerolineas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MejoresTodasLasAerolineas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MejoresTodasLasAerolineas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MejoresTodasLasAerolineas("","","","",0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label NroEscalas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label labelAeropuertoD;
    private java.awt.Label labelAeropuertoO;
    private java.awt.Label labelEscalas;
    private javax.swing.JTable tableVuelos;
    // End of variables declaration//GEN-END:variables
}
